# COSC326
# Etude 2: Syllables
# Shaun Kerr, Kurt Weston, James Douglas, Paul Souter
# ===
# Makefile

CC = ghc
FILES = syll.hs
BIN = syll
FLAGS = -Wall

build: $(FILES)
	$(CC) -o $(BIN) $(FLAGS) $(FILES)
