#pragma once
#ifndef Shapes_HPP
#define Shapes_HPP

class Shapes{
public:

	void shape1(int *carpet[], int startlocx, int startlocy);
	void shape2(int **carpet, int startlocx, int startlocy);
	void shape3(int **carpet, int startlocx, int startlocy);
	void shape4(int **carpet, int startlocx, int startlocy);
	void shape5(int **carpet, int startlocx, int startlocy);
	void shape6(int **carpet, int startlocx, int startlocy);
	void shape7(int **carpet, int startlocx, int startlocy);
	void shape8(int **carpet, int startlocx, int startlocy);
	void shape9(int **carpet, int startlocx, int startlocy);
	void shape10(int **carpet, int startlocx, int startlocy);
	void shape11(int **carpet, int startlocx, int startlocy);
	void shape12(int **carpet, int startlocx, int startlocy);
	void shape13(int **carpet, int startlocx, int startlocy);
	void shape14(int **carpet, int startlocx, int startlocy);
	void shape15(int **carpet, int startlocx, int startlocy);
	void shape16(int **carpet, int startlocx, int startlocy);
	void shape17(int **carpet, int startlocx, int startlocy);
	void shape18(int **carpet, int startlocx, int startlocy);
	void shape19(int **carpet, int startlocx, int startlocy);
};
#endif // !1
